language: c

compiler:
  - gcc
  - clang

integrations:
  notifications:
    - integrationName: email
      type: email
      on_success: never
      on_failure: never
      on_cancel: never
      on_pull_request: never

env:
    - CONF="--disable-test-perf"
    - CONF="--disable-abi-compat --disable-test-perf"

build:
  ci:
    - rm -f /etc/apt/sources.list.d/basho_riak.list
    - apt-get update
    - apt-get install --no-install-recommends -yy asciidoctor autoconf automake build-essential ccache clang doxygen gcc graphviz libconfig-dev libcunit1-dev libnuma-dev libpcap-dev libssl-dev libtool mscgen xsltproc
    - mkdir -p $HOME/odp-shmdir
    - export CI=true ODP_SHM_DIR=$HOME/odp-shmdir ODP_TEST_OUT_XML=yes
    - ./bootstrap
    - if [ "${CC#clang}" != "${CC}" ] ; then export CXX="${CC/clang/clang++}"; fi
    - echo ./configure $CONF
    - ./configure $CONF
    - make -j $(nproc)
    # Run tests only with GCC
    - |
      if [ "${CC}" == "gcc" ] ; then
        echo "=== Running test suite with basic scheduler ===";
        ODP_SCHEDULER=basic make check;
        ./scripts/shippable-post.sh basic;
        echo "=== Running test suite with sp scheduler ===";
        ODP_SCHEDULER=sp make check;
        ./scripts/shippable-post.sh sp;
        echo "=== Running test suite with scalable scheduler ===";
        ODP_SCHEDULER=scalable make check;
        ./scripts/shippable-post.sh scalable;
      fi
    - rm -rf $HOME/odp-shmdir

  on_failure:
    - ./scripts/shippable-post.sh
    - cat config.log
    - find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done
