name: 'Run Failure Logger'
description: 'Log output of failing run'
runs:
  using: 'composite'
  steps:
    - run: find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done
      shell: bash
